### ISSUE TITLE
Info on how to use this script

### ISSUE THREAD

**Issue by KayGt3** [bongiovimatthew-microsoft/pscredentialWithCert#6]
Hello,

I'm trying to figure out how to use the script but without success, I hope someone can help me.

I should start a browser using the credentials contained in the smartcard via the command below, but each time it tells me that the user or password is wrong.

`$cred = Get-SmartCardCred`
`Start-Process "msedge" -Credential $cred`

What am I doing wrong?

Thanks in advance!
Marco

**Comment by jimmy58663** [comment]
Hey,

@KayGt3 this is kind of a two-fold problem going on. The first issue is that Start-Process does not support smart card credentials in the form of PSCreds. It has to do with how it parses the the Username of the PSCreds and the formatting of a smart card username, it is assuming there is a domain. Good news is I have a work around for that:

```
$Cred = Get-SmartCardCred

$StartInfo = New-Object System.Diagnostics.ProcessStartInfo
$StartInfo.FileName = 'explorer.exe'
$StartInfo.UseShellExecute = $false
$StartInfo.UserName = $Cred.Username
$StartInfo.Password = $Cred.Password
$StartInfo.WorkingDirectory = $env:windir
$StartInfo.Arguments = 'shell:Appsfolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge'

$Process = New-Object System.Diagnostics.Process
$Process.StartInfo = $StartInfo
$Process.Start()

$Cred = $null
```

The second issue here is that MS Edge is apparently not a typical .exe that you can launch and has to be launched via explorer.exe. I am not sure of the exact details behind it, but you apparently cannot launch explorer.exe as a second user inside of windows. I am not able to test whether or not Edge will run as another user until tomorrow, but I suspect you cannot since it is spawned off of explorer.exe. If you are able to test it out today let me know.

**Comment by KayGt3** [comment]
Thanks for your reply, i'll be able to test tomorrow because now i'm at home, I'll let you know.
With Edge i mean the new Chronium Edge, so i guess can be handle as a normal .exe
Thanks again!

**Comment by jimmy58663** [comment]
Ahh, yes I downloaded the Chromium Edge and it is an executable. I did have to use the fully qualified path to the exe in $StartInfo.FileName and you will not need to use the $StartInfo.Arguments for it.

**Comment by KayGt3** [comment]
Hello, i try the script but is not working.

The script ask me to choose a smartcard, i type the PIN and it opens the program but when I browse an SSO website it keeps asking me for credentials or I can't navigate at all, as if it doesn't recognize the user.

```
$Cred = Get-SmartCardCred

$StartInfo = New-Object System.Diagnostics.ProcessStartInfo
$StartInfo.FileName = 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'
$StartInfo.UseShellExecute = $false
$StartInfo.UserName = $Cred.Username
$StartInfo.Password = $Cred.Password
$StartInfo.WorkingDirectory = $env:windir

$Process = New-Object System.Diagnostics.Process
$Process.StartInfo = $StartInfo
$Process.Start()

$Cred = $null
```

**Comment by jimmy58663** [comment]
Not sure for certain what is causing those issues as it could just be the website itself. Things you can try:

1. Change the WorkingDirectory to 'C:\Program Files (x86)\Microsoft\Edge\Application' as Edge may be trying to reference libraries with relative paths.
2. Change your filename to 'powershell.exe' and add 
`$StartInfo.Arguments = 'Start-Process msedge'`
This may help because it launches powershell with your smart card credentials and then from that instance launches a msedge process with those same credentials without having to access the smart card.

On another note, is this something that has to be launched from PowerShell? You should be able to Shift+Right-click the msedge.exe file and run as a different user.

**Comment by KayGt3** [comment]
Let me explain better, we have some pc where the logged on user is generic and when the user has to request holidays, insert the badge and open a link to an internal website.

With Shift+Right-click it works but i wanted something easier for users.

Unfortunately the result is the same, i tried different website but the user is not recognized.

```
$StartInfo = New-Object System.Diagnostics.ProcessStartInfo
$StartInfo.FileName = 'powershell.exe'
$StartInfo.UseShellExecute = $false
$StartInfo.UserName = $Cred.Username
$StartInfo.Password = $Cred.Password
$StartInfo.WorkingDirectory = 'C:\Program Files (x86)\Microsoft\Edge\Application'
$StartInfo.Arguments = 'Start-Process msedge'

$Process = New-Object System.Diagnostics.Process
$Process.StartInfo = $StartInfo
$Process.Start()

$Cred = $null
```

**Comment by KayGt3** [comment]
UPDATE
If tell to the script to open the powershell console and i execute the command `$env:username` returns me the correct username (what the smartcard is referring to) but it show this error:

Error during reading or writing the history file 'C:\Users\Default\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadline\ConsoleHost_history.txt': Access to the path 'C:\Users\Default\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadline' denied.

The strange behaviour is related to the path C:\Users\Default instead of C:\Users\USERNAME.
I was able to make it work with a user who has a virtual smartcard, this user has a physical smartcard. Tomorrow i'm in the office so i can try with other users and smartcards.

Thanks for your effort!
